In [2]:
import pandas as pd
df=pd.read_csv('luxury_cosmetics_popups.csv')
df

,event_id,brand,region,city,location_type,event_type,start_date,end_date,lease_length_days,sku,product_name,price_usd,avg_daily_footfall,units_sold,sell_through_pct
0,POP100282,Charlotte Tilbury,North America,Miami,Art/Design District,Flash Event,2024-02-25,2024-03-02,6,LE-UQYNQA1A,Charlotte Tilbury Glow Mascara,62.21,1107,3056,98.90
1,POP102014,Valentino Beauty,North America,New York,Airport Duty-Free,Flash Event,2024-03-17,2024-06-09,84,LE-9E9FTDSM,Valentino Beauty Pearl Eyeshadow Palette,77.93,1652,2782,86.32
2,POP101719,YSL Beauty,Europe,Berlin,Airport Duty-Free,Standalone Pop-Up,2025-02-26,2025-03-10,12,LE-W921CLUG,YSL Beauty Glow Eyeshadow Palette,149.91,752,2720,69.18
3,POP100994,Hermès Beauty,North America,Chicago,Airport Duty-Free,Standalone Pop-Up,2025-07-06,2025-08-04,29,LE-MPO4BX6H,Hermès Beauty Pearl Highlighter,80.32,1688,203,66.78
4,POP102033,Tom Ford Beauty,Europe,London,High-Street,Shop-in-Shop,2024-12-06,2024-12-25,19,LE-M3D94MYP,Tom Ford Beauty Noir Highlighter,56.15,1012,1292,80.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2128,POP101638,Dior,North America,Toronto,Department Store Atrium,Shop-in-Shop,2024-09-19,2024-11-23,65,LE-J7KHKHWQ,Dior Glow Primer,44.27,1668,1180,64.06
2129,POP101095,Guerlain,Middle East,Dubai,Department Store Atrium,Shop-in-Shop,2024-08-07,2024-09-09,33,LE-H9OI4HZZ,Guerlain Satin Primer,63.66,1350,1293,69.00
2130,POP101130,Givenchy Beauty,North America,Toronto,Airport Duty-Free,Standalone Pop-Up,2025-01-14,2025-04-05,81,LE-NDYDZF2H,Givenchy Beauty Pearl Blush,38.68,2121,793,79.30
2131,POP101294,Tom Ford Beauty,Europe,Paris,Art/Design District,Mall Kiosk,2024-03-02,2024-04-10,39,LE-JOHHW772,Tom Ford Beauty Pearl Primer,53.40,1210,548,70.71
2132,POP100860,Hourglass,Europe,Madrid,Art/Design District,Shop-in-Shop,2025-04-12,2025-05-14,32,LE-Y7ER964W,Hourglass Opulence Mascara,58.29,987,2206,75.81

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id            2133 non-null   object
 1   brand               2133 non-null   object
 2   region              2133 non-null   object
 3   city                2086 non-null   object
 4   location_type       2133 non-null   object
 5   event_type          2133 non-null   object
 6   start_date          2133 non-null   datetime64[ns]
 7   end_date            2097 non-null   datetime64[ns]
 8   lease_length_days   2133 non-null   int64
 9   sku                 2133 non-null   object
 10  product_name        2133 non-null   object
 11  price_usd           2133 non-null   float64
 12  avg_daily_footfall  2133 non-null   int64
 13  units_sold          2133 non-null   int64
 14  sell_through_pct    2133 non-null   float64
 15  revenue             2133 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(8)
memory usage: 266.8+ KB

In [ ]:
df['start_date']=pd.to_datetime(df['start_date'])

In [10]:
df['end_date']=pd.to_datetime(df['end_date'])

In [6]:
df['revenue']=df['price_usd']*df['units_sold']

In [12]:
df['city'].fillna('Unkown', inplace=True)

In [13]:
df['end_date'].fillna(df['start_date'], inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id            2133 non-null   object
 1   brand               2133 non-null   object
 2   region              2133 non-null   object
 3   city                2133 non-null   object
 4   location_type       2133 non-null   object
 5   event_type          2133 non-null   object
 6   start_date          2133 non-null   datetime64[ns]
 7   end_date            2133 non-null   datetime64[ns]
 8   lease_length_days   2133 non-null   int64
 9   sku                 2133 non-null   object
 10  product_name        2133 non-null   object
 11  price_usd           2133 non-null   float64
 12  avg_daily_footfall  2133 non-null   int64
 13  units_sold          2133 non-null   int64
 14  sell_through_pct    2133 non-null   float64
 15  revenue             2133 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(8)
memory usage: 266.8+ KB

In [9]:
df[['brand', 'product_name', 'price_usd', 'units_sold', 'revenue']].head(10)

,brand,product_name,price_usd,units_sold,revenue
0,Charlotte Tilbury,Charlotte Tilbury Glow Mascara,62.21,3056,190113.76
1,Valentino Beauty,Valentino Beauty Pearl Eyeshadow Palette,77.93,2782,216801.26
2,YSL Beauty,YSL Beauty Glow Eyeshadow Palette,149.91,2720,407755.20
3,Hermès Beauty,Hermès Beauty Pearl Highlighter,80.32,203,16304.96
4,Tom Ford Beauty,Tom Ford Beauty Noir Highlighter,56.15,1292,72545.80
5,Givenchy Beauty,Givenchy Beauty Opulence Lipstick,38.53,489,18841.17
6,Guerlain,Guerlain Satin Blush,64.51,594,38318.94
7,Rare Beauty,Rare Beauty Lumière Setting Powder,58.70,2480,145576.00
8,Pat McGrath Labs,Pat McGrath Labs Satin Blush,47.17,1574,74245.58
9,Estée Lauder,Estée Lauder Mirage Highlighter,47.71,2538,121087.98

In [4]:
df.describe()

,lease_length_days,price_usd,avg_daily_footfall,units_sold,sell_through_pct
count,2133.000000,2133.000000,2133.000000,2133.000000,2133.000000
mean,46.792780,96.562916,1407.105954,1937.404594,73.233788
std,25.315425,74.681231,542.245867,1101.797964,14.602901
min,3.000000,30.040000,439.000000,101.000000,39.500000
25%,25.000000,52.330000,989.000000,1024.000000,61.740000
50%,46.000000,68.360000,1323.000000,1839.000000,73.030000
75%,69.000000,106.370000,1763.000000,2731.000000,85.210000
max,90.000000,396.490000,3082.000000,4897.000000,100.000000

In [23]:
df.groupby('brand')['price_usd'].sum().sort_values()

brand
Dior                   6899.66
Givenchy Beauty        6916.34
Fenty Beauty           7009.65
La Prairie             7313.83
Lancôme                7634.49
NARS                   7671.80
Hermès Beauty          8028.93
Charlotte Tilbury      8279.92
Bobbi Brown            8533.21
Valentino Beauty       8535.59
Guerlain               8670.52
MAC Cosmetics          8693.63
Rare Beauty            8703.86
Shiseido               8775.64
Chanel                 8818.95
Tom Ford Beauty        8977.05
Pat McGrath Labs       8990.37
Sisley-Paris           9284.40
Armani Beauty          9327.93
Clé de Peau Beauté     9456.05
Huda Beauty            9516.89
Estée Lauder           9937.66
YSL Beauty             9969.67
Hourglass             10022.66
Name: price_usd, dtype: float64

In [ ]:
brand_revenue=